---
abstract: 'WebSocket client for AnyEvent'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  Protocol::WebSocket::Handshake::Server: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300037, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-WebSocket-Client
no_index:
  directory:
    - example
requires:
  AnyEvent: 0
  AnyEvent::Handle: 0
  AnyEvent::Socket: 0
  Moo: 0
  PerlX::Maybe: 0.003
  Protocol::WebSocket::Frame: 0
  Protocol::WebSocket::Handshake::Client: 0
  Scalar::Util: 0
  URI: 0
  URI::ws: 0
  perl: v5.10.0
resources:
  bugtracker: https://github.com/plicease/anyevent-websocket-client/issues
  homepage: http://perl.wdlabs.com/AnyEvent-WebSocket-Client/
  repository: git://github.com/plicease/anyevent-websocket-client.git
version: 0.06
