---
abstract: 'WebSocket client for AnyEvent'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  FindBin: '0'
  Module::Build: '0.3601'
  Protocol::WebSocket: '0.15'
  Test::More: '0.94'
configure_requires:
  Module::Build: '0.3601'
dynamic_config: 1
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: AnyEvent-WebSocket-Client
no_index:
  directory:
    - example
recommends:
  EV: '0'
  IO::Socket::SSL: '0'
  Math::Random::Secure: '0'
  Net::SSLeay: '0'
  PerlX::Maybe::XS: '0'
requires:
  AE: '0'
  AnyEvent: '0'
  Carp: '0'
  Encode: '0'
  Moo: '1.001000'
  PerlX::Maybe: '0.003'
  Protocol::WebSocket: '0.15'
  URI: '0'
  URI::ws: '0'
  perl: '5.008'
resources:
  bugtracker: https://github.com/plicease/AnyEvent-WebSocket-Client/issues
  homepage: http://perl.wdlabs.com/AnyEvent-WebSocket-Client
  repository: git://github.com/plicease/AnyEvent-WebSocket-Client.git
version: '0.26'
